include: https://gitlab.sensirion.lokal/Sensirion/Python/ci-config-python/raw/master/gitlab-ci-template-v2.yml

check_rst_syntax:
  extends: .check_rst_syntax_v2

check_editorconfig:
  extends: .check_editorconfig_v2

py3p8_linux_sdist:
  extends: .py3p8_linux_sdist_v2

py3p6_linux_build:
  extends: .py3p6_linux_build_v2

py3p8_linux_build:
  extends: .py3p8_linux_build_v2

py3p8_64bit_win_build:
  extends: .py3p8_64bit_win_docker_build_v2

build_docs:
  extends: .build_docs_v2

deploy_staging:
  extends: .deploy_staging_v2

deploy_stable:
  extends: .deploy_stable_v2
  environment:
    name: pypi.org
    url: https://pypi.org/project/sensirion-driver-support-types/
  before_script:
    - pip install twine~=1.12.1
  script:
    - PKG_VERSION=$(python setup.py --version --quiet | tail -n1)
    - TAG_VERSION=$(git describe --tags)
    - if [ "$TAG_VERSION" != "$PKG_VERSION" ]; then echo "Tag Version ($TAG_VERSION) != Package Version ($PKG_VERSION)" && exit 1; fi
    - twine upload dist/*

# Deploy all files within the "public" directory of the artifacts from the jobs
# specified as dependencies. Job must be named pages, otherwise gitlab does
# not deploy to gitlab pages.
pages:
  extends: .deploy_pages_v2
  dependencies: [build_docs]
